baseURL = "https://sachinkottarathodi.com/"
languageCode = "en-us"
title = " Sachin Kottarathodi's Space"
theme = "notrack"
pagination.pagerSize = 4  # Posts per page, e.g. in the blog

[params]
author = "Sachin Kottarathodi"
siteHeading = " Sachin Kottarathodi's Space"  # Professional headline
favicon = "img/favicon.ico"  # Update this if you have a custom icon
showTaxonomyLinks = false  # No category buttons for now


# Blog display settings
showBlogLatest = true
mainSections = ["blog"]
blogLatestHeading = "Insights & Learning"
nBlogLatest = 10  # Number of blog posts in summary

[params.social]
github = "sachin-kottarathodi"
linkedin = "ksachin1"
email = "sachin.kottarathodi@gmail.com"


[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokailight" # or "github", "friendly", "tango", etc.
